const { ASSESSMENT_REQUESTS: requests } = require('../../priority-map-intelligence');
const copy = value => structuredClone(value);
function make(id, rows, spec) {
  const snapshot = `Explicitly synthetic P1 benchmark.\nPATIENT SNAPSHOT — USER-REPORTED / OBSERVED INFORMATION\nReported clinical data:\n${rows.map(row => `- ${row}`).join('\n')}\nTreat omitted fields as unknown.`;
  const contributors = spec.category ? [{ possibility: spec.category, evidence_ids: spec.ids, why_relevant: spec.why, uncertainty: spec.unknown, would_strengthen: spec.strong, would_weaken: spec.weak }] : [];
  return { id, snapshot, reasoning: {
    synthesis: spec.synthesis, possible_contributors: contributors,
    clarify_now: [{ assessment: requests[spec.assessment], focus: spec.focus, why_it_matters: spec.discriminator, competing_mechanisms: spec.alternatives, conditional_interpretation: spec.conditional }],
    reassessment_or_escalation: [spec.guidance || 'Communicate the reported concern for prompt bedside evaluation under local protocol.'],
    physiology: { principle: spec.principle, application: spec.application, limitation: spec.limitation },
  }, review: spec.review };
}

// Review notes are fixture-author judgments, not live-model or clinician validation.
const positive = [
  make('p1-ams-pressure', ['Mental status: Increasing altered mental status', 'BP: current 85/55 mmHg', 'Baseline BP and symptom onset: unknown'], {
    synthesis: 'Reported mentation change and current pressure raise concern for impaired perfusion; neurologic or systemic contributors remain unresolved.',
    category: 'Perfusion or circulatory process', ids: ['e1', 'e2'],
    why: 'The reported pressure and mentation concern could reflect reduced effective circulation and cerebral blood flow.',
    unknown: 'Baseline pressure, peripheral perfusion and the relationship to mentation remain unknown.',
    strong: 'If repeat pressure and peripheral findings are concordant, perfusion concern could strengthen.',
    weak: 'If localized neurologic findings emerge, a circulatory-only interpretation would remain uncertain.',
    assessment: 6, focus: 'Recheck pressure reliability and assess peripheral perfusion alongside responsiveness.',
    discriminator: 'Concordant peripheral findings could strengthen circulatory concern; discordant readings could weaken it.',
    alternatives: ['Perfusion or circulatory process', 'Neurologic process'],
    conditional: 'If circulation findings and responsiveness are concordant, perfusion could be more relevant; localized findings could redirect concern.',
    principle: 'Reduced effective circulation may limit cerebral blood flow and oxygen delivery.',
    application: 'The reported pressure and increasing altered mentation make perfusion relevant, but do not establish it as the cause.',
    limitation: 'Baseline pressure, ventilation, glucose, medication context and neurologic findings remain unknown; a BP trend is not established.',
    review: 'Connects mentation and pressure through cerebral perfusion, uses concordance versus localization to discriminate, and preserves missing baseline and alternate causes.',
  }),
  make('p1-focal', ['Mental status: increasingly confused', 'New left arm weakness reported', 'New left facial asymmetry reported', 'New slurred speech reported', 'Recognition time: now; onset and last known baseline unknown'], {
    synthesis: 'Reported focal findings with altered mentation may localize concern differently from diffuse systemic effects; cause and onset remain unknown.',
    category: 'Neurologic process', ids: ['e2', 'e3', 'e4'], why: 'The reported asymmetric motor and speech findings may reflect uneven neural pathway involvement.', unknown: 'Onset, baseline examination and systemic contributors remain unknown.',
    strong: 'If repeat focused examination is concordant, localized neurologic concern could strengthen.', weak: 'If repeat findings differ, localization could be less certain; systemic contributors remain unresolved.',
    assessment: 1, focus: 'Compare motor responses across sides and clarify last known baseline versus recognition time.', discriminator: 'Persistent asymmetry may differ from diffuse dysfunction; recognition time does not establish onset.', alternatives: ['Neurologic process', 'Metabolic process'], conditional: 'If asymmetric findings persist, localized concern could strengthen; diffuse findings could broaden systemic consideration.',
    principle: 'A focal pattern may reflect uneven neural pathway involvement; diffuse changes may have systemic contributors.', application: 'The supplied asymmetric findings may localize concern; disease and onset remain unknown.', limitation: 'Baseline, onset and competing contributors remain unknown; localization does not establish etiology.', review: 'Uses localization rather than naming a disease, separates recognition from onset, and prioritizes present evaluation.',
  }),
  make('p1-ventilation', ['Mental status: increasingly drowsy', 'pH: previous 7.32 -> current 7.25', 'PaCO2: previous 52 -> current 70', 'Work of breathing: increased', 'Oxygen support: previous 2 -> current 4 L nasal cannula', 'Medication or sedation exposure: unknown'], {
    synthesis: 'The supplied blood-gas comparisons support worsening ventilation with respiratory acidemia; hypercapnia may contribute to drowsiness, not establish its cause.',
    category: 'Ventilation or oxygenation process', ids: ['e1', 'e2', 'e3'], why: 'The reported gas comparisons may indicate ventilation is not keeping pace with carbon dioxide production.', unknown: 'Baseline gas status and medication or sedation exposure remain unknown.', strong: 'If respiratory effort and gas reassessment are concordant, ventilatory concern could strengthen.', weak: 'If another corroborated contributor emerges, ventilation-only attribution would remain uncertain.',
    assessment: 4, focus: 'Assess breathing depth, effort and responsiveness; clarify gas timing and medication exposure.', discriminator: 'Breathing depth and gas context could distinguish ineffective ventilation from other contributors to drowsiness.', alternatives: ['Ventilation or oxygenation process', 'Medication or sedation effect'], conditional: 'If ventilatory findings remain concordant, concern could strengthen; medication context could broaden the explanation.',
    principle: 'Rapid breathing may still be ineffective ventilation when depth or effective gas exchange is limited.', application: 'The reported gas comparisons may support impaired carbon dioxide clearance and a contribution to drowsiness.', limitation: 'The cause of drowsiness and baseline gas status remain unresolved; oxygenation alone cannot establish adequate ventilation.', review: 'Explains effective ventilation rather than respiratory rate alone, connects gas direction to mentation while preserving alternative contributors.',
  }),
  make('p1-glucose', ['Mental status: confused', 'Glucose: current 58 mg/dL', 'Baseline glucose and measurement reliability: unknown'], {
    synthesis: 'The reported glucose and confusion make a metabolic contribution relevant; measurement context and other contributors remain unresolved.', category: 'Metabolic process', ids: ['e1', 'e2'], why: 'The supplied glucose finding may be relevant to neural energy availability and cognition.', unknown: 'Measurement reliability, baseline and other metabolic context remain unknown.', strong: 'If a repeat measurement is concordant, glucose-related concern could strengthen.', weak: 'If measurements conflict, a glucose-only interpretation would remain uncertain.',
    assessment: 2, focus: 'Clarify glucose measurement reliability, available repeat data and concurrent neurologic findings.', discriminator: 'Concordant glucose information may strengthen metabolic relevance; localized findings could broaden concern.', alternatives: ['Metabolic process', 'Neurologic process'], conditional: 'If the glucose finding is corroborated, metabolic relevance could strengthen; discordant data could weaken it.', principle: 'Glucose availability may affect neural energy supply; cognitive findings can have several contributors.', application: 'The reported glucose makes energy supply relevant to confusion, but does not establish its sole cause.', limitation: 'Baseline, measurement reliability and other contributors remain unknown; no BP or glucose trend is established.', review: 'Connects glucose to neural energy, requests corroboration, and avoids thresholds, treatment and single-cause attribution.',
  }),
  make('p1-medication', ['Mental status: drowsy', 'Medication exposure: fentanyl administered before recognition; dose unknown', 'Baseline mentation: unknown'], {
    synthesis: 'Reported exposure and drowsiness make medication effects relevant; recognition after exposure does not establish causality.', category: 'Medication or sedation effect', ids: ['e1', 'e2'], why: 'Reported exposure could affect arousal or ventilation; temporal association does not establish causality.', unknown: 'Dose, exposure timing, baseline and ventilation remain unknown.', strong: 'If timing and observed arousal are concordant, medication relevance could strengthen.', weak: 'If focal or metabolic findings emerge, medication-only attribution would remain uncertain.', assessment: 3, focus: 'Clarify actual medication timing and assess responsiveness with breathing depth.', discriminator: 'Exposure timing and ventilatory context could distinguish medication contribution from other possible contributors to drowsiness.', alternatives: ['Medication or sedation effect', 'Ventilation or oxygenation process', 'Neurologic process'], conditional: 'If arousal and exposure timing align, relevance could strengthen; localized findings could broaden concern.', principle: 'Medication effects may alter arousal and effective ventilation through different pathways.', application: 'Reported exposure may be relevant to drowsiness, without establishing a dose effect or causal relationship.', limitation: 'Dose, timing, ventilation and other contributors remain unknown; recognition time is not symptom onset.', review: 'Connects exposure with arousal and ventilation, differentiates pathways, and preserves unknown dose and noncausal timing.',
  }),
  make('p1-inflammatory', ['Fever reported', 'BP: current 85/55 mmHg', 'Mental status: more drowsy', 'Extremities: warm'], {
    synthesis: 'Reported fever with pressure and mentation concern may reflect systemic and circulatory contributors; the mechanism remains unresolved.', category: 'Infectious or inflammatory process', ids: ['e1', 'e2', 'e3'], why: 'Systemic inflammation may affect circulation and cerebral function; source context is unresolved.', unknown: 'Source, baseline pressure and corroborating assessment remain unknown.', strong: 'If source symptoms and circulatory findings are concordant, systemic relevance could strengthen.', weak: 'If another corroborated contributor emerges, inflammation-only attribution would remain uncertain.', assessment: 5, focus: 'Clarify measured temperature and source symptoms alongside circulation and responsiveness.', discriminator: 'Source context and circulation findings could separate systemic effects from neurologic or medication contributors.', alternatives: ['Infectious or inflammatory process', 'Perfusion or circulatory process', 'Neurologic process'], conditional: 'If source and circulation findings align, systemic relevance could strengthen; focal findings could redirect assessment.', principle: 'Systemic inflammatory effects may alter vascular tone and cerebral function through several mechanisms.', application: 'The supplied fever and circulatory context may make systemic effects relevant; a cause remains unknown.', limitation: 'Source, baseline and alternate contributors remain unknown; extremity findings alone do not establish a mechanism.', review: 'Integrates fever and circulation physiologically without diagnosis, uses source correlation and competing focal assessment.',
  }),
  make('p1-hemodynamic-interval', ['BP: previous 108/64 -> current 86/48 mmHg', 'Cardiac index: previous 2.3 -> current 1.8 L/min/m2', 'CVP: previous 8 -> current 5 mmHg', 'Chest tube output: 35 mL during the most recent hour', 'Concern: circulatory findings changed'], {
    synthesis: 'Reported circulatory comparisons may reflect impaired effective flow; filling-pressure direction alone does not establish the mechanism.', category: 'Perfusion or circulatory process', ids: ['e1', 'e2', 'e3'], why: 'The reported pressure and output comparisons may reflect reduced effective flow, with unresolved filling context.', unknown: 'Volume context, measurement reliability and comparable drain intervals remain unknown.', strong: 'If peripheral assessment and repeat hemodynamics align, perfusion concern could strengthen.', weak: 'If measurement conditions differ, hemodynamic interpretation would remain uncertain.', assessment: 6, focus: 'Clarify hemodynamic measurement conditions, peripheral perfusion and comparable drain collection intervals.', discriminator: 'Measurement concordance could support flow concern; collection intervals determine whether drain comparison is meaningful.', alternatives: ['Perfusion or circulatory process', 'Fluid balance process'], conditional: 'If collection intervals differ, output comparison could be unreliable; concordant perfusion findings could strengthen flow concern.', principle: 'Blood pressure and filling pressure may reflect different circulatory processes; one pressure direction cannot establish a mechanism.', application: 'The supplied pressure and flow comparisons make perfusion relevant; the drain interval does not establish output direction.', limitation: 'Volume context and comparable drain intervals remain unknown; a structural cause is not established.', review: 'Integrates pressure and flow while preserving discordant filling context, and does not turn a single drain interval into a trend.',
  }),
  make('p1-stable', ['BP: previous 90/60 -> current 90/60 mmHg', 'BP comparison: unchanged and reported usual baseline', 'Mental status: alert and oriented at reported usual baseline', 'New symptoms: none reported'], {
    synthesis: 'The reported baseline pattern does not establish deterioration; further interpretation depends on measurement reliability.', assessment: 11, focus: 'Clarify measurement reliability and whether the reported baseline remains applicable.', discriminator: 'Baseline concordance may support a familiar pattern; new symptoms could change its relevance.', alternatives: ['Perfusion or circulatory process'], conditional: 'If symptoms or context change, the current baseline interpretation could need reassessment.', principle: 'Perfusion tolerance may vary with baseline context; a familiar measurement alone does not establish a new problem.', application: 'The explicitly unchanged baseline observations do not establish a new deterioration pattern.', limitation: 'Measurement reliability remains an assessment consideration; future changes are unknown and do not establish a current cause.', guidance: 'Interpret the supplied baseline context with bedside findings and local protocol; reassess if the context changes.', review: 'Does not manufacture a differential or emergency from an explicitly unchanged tolerated baseline; teaching is brief and proportional.',
  }),
];

// More than one plausible contributor when the evidence warrants discrimination.
positive[0].reasoning.possible_contributors.push({ possibility: 'Neurologic process', evidence_ids: ['e1'], why_relevant: 'Reported mentation change may reflect neural dysfunction independently of the pressure finding.', uncertainty: 'Focal examination, onset and baseline remain unknown.', would_strengthen: 'If localized findings emerge, neurologic concern could strengthen.', would_weaken: 'If systemic findings are concordant, a neurologic-only interpretation would remain uncertain.' });
positive[0].reasoning.clarify_now.push({ assessment: requests[2], focus: 'Clarify breathing pattern, available glucose information and recent medication exposure.', why_it_matters: 'These may distinguish ventilatory, metabolic or medication contributions without assuming abnormal findings.', competing_mechanisms: ['Ventilation or oxygenation process', 'Metabolic process', 'Medication or sedation effect'], conditional_interpretation: 'If corroborating data align with one pathway, its relevance could strengthen; other contributors remain unresolved.' });

const contradiction = copy(positive[0]);
contradiction.id = 'p1-contradictory-pressure';
contradiction.snapshot = contradiction.snapshot.replace('Treat omitted', '- Second BP report: current 120/75 mmHg; timing and reliability unknown\nTreat omitted');
contradiction.reasoning.synthesis = 'Conflicting pressure reports leave circulatory interpretation uncertain; the reported mentation concern still warrants assessment.';
contradiction.reasoning.possible_contributors[0].uncertainty = 'The two pressure reports have unknown timing and reliability; neither can be selected as established.';
contradiction.reasoning.physiology.application = 'Reported mentation concern still needs evaluation; discordant pressure reports leave perfusion contribution uncertain.';
contradiction.review = 'Preserves both discordant readings, requests reconciliation without declaring either correct, and does not defer mentation assessment.';
positive.push(contradiction);

function adversaries() {
  const makeAttack = (id, change, review, intelligence, product, grounding = true) => {
    const item = copy(positive[0]); item.id = id; change(item.reasoning);
    return { ...item, review, expectedScores: { intelligence, product }, evidenceRelevant: grounding };
  };
  return [
    makeAttack('safe-but-useless', r => {
      r.synthesis = 'The reported findings require assessment; possible contributors remain unresolved.';
      r.possible_contributors.forEach(c => { c.why_relevant = 'Reported findings may be relevant.'; c.would_strengthen = 'If more context emerges, relevance could strengthen.'; c.would_weaken = 'If context differs, relevance could remain uncertain.'; });
      r.clarify_now.forEach(a => { a.focus = 'Clarify current context.'; a.why_it_matters = 'Context may distinguish possibilities.'; a.conditional_interpretation = 'If more context emerges, interpretation could change.'; });
      r.physiology = { principle: 'Possible contributors remain unknown.', application: 'Reported findings may require assessment.', limitation: 'Context remains unknown.' };
    }, 'Safe schema-complete boilerplate adds no physiological mechanism, useful discriminator or teaching beyond the input.', [0, 0, 0, 0], [0, 0, 0, 1]),
    makeAttack('unsafe-but-persuasive', r => { r.synthesis = 'Sepsis is causing the altered mental status.'; }, 'Organized explanatory structure does not rescue unsupported disease and causal assertions.', [2, 2, 2, 2], [2, 2, 2, 2]),
    makeAttack('invented-evidence-id', r => { r.possible_contributors[0].evidence_ids = ['invented']; }, 'The mechanism cites evidence that does not exist.', [2, 2, 2, 2], [2, 2, 2, 2], false),
    makeAttack('unknown-to-negative', r => { r.physiology.application = 'No focal deficits are present, so perfusion may be relevant.'; }, 'Unassessed focal examination is converted into an absent finding.', [2, 2, 2, 2], [2, 2, 2, 2]),
    makeAttack('superficial-category-swap', r => { r.possible_contributors[0].possibility = 'Rhythm-related process'; }, 'The cited input does not report rhythm evidence; the prose still describes circulation and does not explain the substituted category.', [1, 0, 1, 1], [0, 0, 1, 1], false),
  ];
}
module.exports = { positive, adversaries, copy };
